// <auto-generated />
using System;
using CoreDFeMonitor.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoreDFeMonitor.Infrastructure.Migrations
{
    [DbContext(typeof(DFeMonitorDbContext))]
    [Migration("20260330161141_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.5");

            modelBuilder.Entity("CoreDFeMonitor.Core.Entities.Documento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ChaveAcesso")
                        .IsRequired()
                        .HasMaxLength(44)
                        .HasColumnType("TEXT");

                    b.Property<bool>("CienciaEnviada")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("DataEmissao")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("DataProcessamento")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("EmpresaId")
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeEvento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Nsu")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT");

                    b.Property<string>("Schema")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoDocumento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("TipoEvento")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("XmlConteudo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("EmpresaId", "Nsu")
                        .IsUnique();

                    b.ToTable("Documentos", (string)null);
                });

            modelBuilder.Entity("CoreDFeMonitor.Core.Entities.Empresa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Bairro")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CaminhoCertificado")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cep")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("TEXT");

                    b.Property<long?>("CodigoMunicipio")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Complemento")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("InscricaoEstadual")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Logradouro")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("NomeMunicipio")
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("Numero")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("RazaoSocial")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("SenhaCertificado")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Uf")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("TEXT");

                    b.Property<string>("UltimoNsu")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("000000000000000");

                    b.Property<string>("UltimoNsuCte")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(15)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("000000000000000");

                    b.HasKey("Id");

                    b.HasIndex("Cnpj")
                        .IsUnique();

                    b.ToTable("Empresas", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
